[[redirects]]
  from = "/api"
  to = "https://www.llama2.ai/api"
  status = 200
  [redirects.headers]
    User-Agent = "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0"
    Accept = "*/*"
    Accept-Language = "de,en-US;q=0.7,en;q=0.3"
    Accept-Encoding = "gzip, deflate, br"
    Referer = "https://www.llama2.ai"
    Content-Type = "text/plain;charset=UTF-8"
    Origin = "https://www.llama2.ai"
    Connection = "keep-alive"
    Sec-Fetch-Dest = "empty"
    Sec-Fetch-Mode = "cors"
    Sec-Fetch-Site = "same-origin"
    Pragma = "no-cache"
    Cache-Control = "no-cache"
    TE = "trailers"


[[redirects]]
  from = "/test"
  to = "https://chess.share.zrok.io"
  status = 200

