name: Build
on: [push, pull_request]

jobs:
  build-windows:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Setup Java
        uses: actions/setup-java@v4

      - run: npm install

      - run: npm run build

      - run: npx cap sync android

      - run: android/gradlew

      - run: |
          ls
          ls android

